spring:
    application:
        name: catalog-service   # The name of the application, used by the config server to filter the configuration
    config:
        import: "configserver:http://localhost:8888"
        request-connect-timeout: 5000
        request-read-timeout: 5000
        fail-fast: true
        retry:
            max-attempts: 6
            initial-interval: 1000
            max-interval: 2000
            multiplier: 1.1


management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,refresh

server:
    port: 9001 
    tomcat:
        connection-timeout: 2s
        keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

atu:
    greeting: Welcome to the local book catalog!